export * from './home'
export * from './main'
export * from './login'
export * from './reset'
export * from './registerReferral'
export * from './registerPassword'
export * from './welcome'
export * from './staticInfo'
